source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '12.0'

target 'DJRxLog' do
  pod 'SnapKit'
  pod 'RxCocoa'
  pod 'RxSwift'

  target 'DJRxLogTests' do
    inherit! :search_paths
  end

  target 'DJRxLogUITests' do
  end

end
